/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rent;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class loginN1 extends javax.swing.JFrame {

    /**
     * Creates new form loginN
     */
    public loginN1() {
        initComponents();
        this.invisible.setVisible(false);
        
    }
    Connection conn;
    PreparedStatement pst;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtusername = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        check = new javax.swing.JCheckBox();
        LoginAsCombo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        invisible = new javax.swing.JLabel();
        visible = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 150, 30));

        jLabel6.setBackground(java.awt.Color.gray);
        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 0));
        jLabel6.setText("User name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 90, 30));
        getContentPane().add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 150, -1));

        jLabel7.setBackground(java.awt.Color.gray);
        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 0));
        jLabel7.setText("Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 90, 20));

        check.setBackground(new java.awt.Color(255, 255, 255));
        check.setForeground(new java.awt.Color(255, 255, 255));
        check.setText("show password");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });
        getContentPane().add(check, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, -1, -1));

        LoginAsCombo.setBackground(new java.awt.Color(122, 189, 189));
        LoginAsCombo.setForeground(new java.awt.Color(0, 204, 204));
        LoginAsCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Staff" }));
        LoginAsCombo.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        LoginAsCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginAsComboActionPerformed(evt);
            }
        });
        getContentPane().add(LoginAsCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 110, 30));

        jButton1.setBackground(new java.awt.Color(186, 172, 172));
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 80, -1));

        jButton2.setBackground(new java.awt.Color(186, 172, 172));
        jButton2.setForeground(new java.awt.Color(0, 102, 102));
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, -1, -1));

        invisible.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\CarRental\\src\\rent\\a2.png")); // NOI18N
        invisible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                invisibleMousePressed(evt);
            }
        });
        getContentPane().add(invisible, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, 30, -1));

        visible.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\CarRental\\src\\rent\\eye_24px.png")); // NOI18N
        visible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                visibleMousePressed(evt);
            }
        });
        getContentPane().add(visible, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, -1, -1));

        jPanel4.setBackground(new java.awt.Color(131, 170, 170));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setForeground(new java.awt.Color(0, 102, 102));
        jButton3.setText("Sign Up");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, -1, 40));

        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newcar/Iro33.jpg"))); // NOI18N
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, -20, 950, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        // TODO add your handling code here:

        if (check.isSelected())

        {
            txtpass.setEchoChar((char)0);
        }else{
            txtpass.setEchoChar('*');
        }
    }//GEN-LAST:event_checkActionPerformed

    private void LoginAsComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginAsComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginAsComboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(txtusername.getText(). equals("") || txtpass.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please fill All Fields");
        }else
        {
            String username = txtusername.getText();
            String pass = txtpass.getText();

            /* if (username.equals("naz")&& pass.equals("123")){
                JOptionPane.showMessageDialog(this,"LOGIN_SUCCESSFULL");
                CarRental m= new CarRental();

                m.setVisible(true);
                this.hide();
            }else{
                JOptionPane.showMessageDialog(this,"username and Password do not match");
            }*/

            ResultSet rs = null;
            char[] passChars = txtpass.getPassword();
            String password = new String(passChars);
            int category = LoginAsCombo.getSelectedIndex() + 1;

            try {

                conn = (Connection) DBAccess.getConnection();
                String sql;
                sql = "SELECT * FROM UserSystem WHERE username='" + txtusername.getText() + "'  AND password='"

                + password + "'AND IDRole='" + category + "'";
                pst = (PreparedStatement) conn.prepareStatement(sql);
                rs = pst.executeQuery();
                if (rs.next()) {
                    UserSystem user = new UserSystem(Integer.parseInt(rs.getString(1)), Integer.parseInt(rs.getString(2)),
                        rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6),
                        rs.getString(7), rs.getString(8), rs.getString(9));
                    JOptionPane.showMessageDialog(this, "LOGIN_SUCCESSFULL");
                    new CarRental().setVisible(true);
                    this.hide();

                } else {
                    JOptionPane.showMessageDialog(this, "LOGIN_FAILURE");

                    txtusername.requestFocus();
                }
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }    catch (ClassNotFoundException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }finally {
                DBAccess.closeConn(null, null, rs);
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed
private void ConfirmExit() {
        int confirmed = JOptionPane.showConfirmDialog(null,
                "Are you sure you want to exit the program?", "Confirm Action",
                JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
            dispose();
        } else {
            setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ConfirmExit();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void invisibleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invisibleMousePressed
        // TODO add your handling code here:
        visible.setVisible(true);
        invisible.setVisible(false);
        txtpass.setEchoChar((char)0);
    }//GEN-LAST:event_invisibleMousePressed

    private void visibleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visibleMousePressed
        // TODO add your handling code here:
        invisible.setVisible(true);
        visible.setVisible(false);
        txtpass.setEchoChar('*');
    }//GEN-LAST:event_visibleMousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        SignUp s = new SignUp();
        s.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginN1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginN1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginN1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginN1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginN1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> LoginAsCombo;
    private javax.swing.JCheckBox check;
    private javax.swing.JLabel invisible;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtusername;
    private javax.swing.JLabel visible;
    // End of variables declaration//GEN-END:variables
}
