/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rent;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class passenger extends javax.swing.JFrame {

    /**
     * Creates new form passenger
     */
    public passenger() {
        initComponents();
        autoID();
        table_update();
    }
    Connection conn;
    PreparedStatement pst;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtmobile = new java.awt.TextField();
        jLabel4 = new javax.swing.JLabel();
        txtaddress = new java.awt.TextArea();
        jLabel3 = new javax.swing.JLabel();
        txtcustname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtregno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(216, 143, 12));
        jTable1.setBorder(null);
        jTable1.setForeground(new java.awt.Color(0, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "PassengerID", " Name", "Address", "Mobile"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(120, 120, 47));
        jTable1.setSelectionBackground(new java.awt.Color(169, 84, 18));
        jTable1.setSelectionForeground(new java.awt.Color(0, 51, 51));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 380, 240));

        jButton4.setBackground(new java.awt.Color(224, 140, 25));
        jButton4.setForeground(new java.awt.Color(0, 51, 51));
        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 100, -1));

        jButton1.setBackground(new java.awt.Color(224, 140, 25));
        jButton1.setForeground(new java.awt.Color(0, 51, 51));
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 100, -1));

        txtmobile.setBackground(new java.awt.Color(238, 237, 237));
        txtmobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmobileActionPerformed(evt);
            }
        });
        getContentPane().add(txtmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 170, 30));

        jLabel4.setBackground(new java.awt.Color(242, 234, 234));
        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(230, 233, 231));
        jLabel4.setText("Mobile");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 49, -1));

        txtaddress.setBackground(new java.awt.Color(238, 237, 237));
        getContentPane().add(txtaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 170, 46));

        jLabel3.setBackground(new java.awt.Color(242, 234, 234));
        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(230, 233, 231));
        jLabel3.setText("Address");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 58, 20));

        txtcustname.setBackground(new java.awt.Color(238, 237, 237));
        txtcustname.setBorder(null);
        txtcustname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcustnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtcustname, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 170, 30));

        jLabel2.setBackground(new java.awt.Color(242, 234, 234));
        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(230, 233, 231));
        jLabel2.setText(" Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 60, 20));

        txtregno.setBackground(new java.awt.Color(238, 237, 237));
        txtregno.setBorder(null);
        txtregno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtregnoActionPerformed(evt);
            }
        });
        getContentPane().add(txtregno, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 170, 30));

        jLabel1.setBackground(new java.awt.Color(242, 234, 234));
        jLabel1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(230, 233, 231));
        jLabel1.setText("Passenger ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 100, -1));

        jLabel6.setBackground(new java.awt.Color(242, 234, 234));
        jLabel6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(230, 233, 231));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newcar/1435b9fe501065db52614223aa86af03.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtmobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmobileActionPerformed

    private void txtcustnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcustnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcustnameActionPerformed

    private void txtregnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtregnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtregnoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new CarRental().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String custID = txtregno.getText();
        String Custname = txtcustname.getText();
        String address = txtaddress.getText();
        String mobile = txtmobile.getText();
        try {
            conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/carrental", "root", "");
            pst = (PreparedStatement) conn.prepareStatement("insert into customer(cust_id,name,address,mobile) values(?,?,?,?)");
            pst.setString(1, custID);
            pst.setString(2, Custname);
            pst.setString(3, address);
            pst.setString(4, mobile);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Customer Added.....");
            txtcustname.setText("");
            txtaddress.setText("");
            txtmobile.setText("");
            txtcustname.requestFocus();
            autoID();
            table_update();
        }catch(SQLException ex){
            Logger.getLogger(carRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel d1 = (DefaultTableModel)jTable1.getModel();
        int selectIndex = jTable1.getSelectedRow();
        txtregno.setText(d1.getValueAt(selectIndex,0).toString());
        txtcustname.setText(d1.getValueAt(selectIndex,1).toString());
        txtaddress.setText(d1.getValueAt(selectIndex,2).toString());
        txtmobile.setText(d1.getValueAt(selectIndex,3).toString());
    }//GEN-LAST:event_jTable1MouseClicked
public void autoID(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            
            conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/carrental", "root", "");
            Statement s = (Statement) conn.createStatement();
            ResultSet rs = s.executeQuery("select Max(cust_id) from customer");
            rs.next();
            rs.getString("Max(cust_id)");
            if(rs.getString("Max(cust_id)")==null){
                txtregno.setText("A0001");
            }else{
               long id = Long.parseLong(rs.getString("Max(cust_id)").substring(2,rs.getString("Max(cust_id)").length()));
                id++;
                txtregno.setText("A0" + String.format("%03d",id));
            }
        
    
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(carRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }catch(SQLException ex){
            Logger.getLogger(carRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
         }public void table_update()
{
    int c;
    try{
       Class.forName("com.mysql.jdbc.Driver");
       conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/carrental", "root", "");
       pst = (PreparedStatement) conn.prepareStatement("select*from customer");
       ResultSet rs = pst.executeQuery();
       ResultSetMetaData rd = rs.getMetaData();
       c= rd.getColumnCount();
       DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
       df.setRowCount(0);
       while(rs.next())
       {
           Vector v2 = new Vector();
           for(int i=1;i<=c;i++){
               v2.add(rs.getString("cust_id"));
               v2.add(rs.getString("name"));
               v2.add(rs.getString("address"));
               v2.add(rs.getString("mobile"));
               
           }
           df.addRow(v2);
           
       }
    }catch(ClassNotFoundException ex){
            Logger.getLogger(carRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }catch (SQLException ex) {
            Logger.getLogger(carRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(passenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(passenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(passenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(passenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new passenger().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.TextArea txtaddress;
    private javax.swing.JTextField txtcustname;
    private java.awt.TextField txtmobile;
    private javax.swing.JTextField txtregno;
    // End of variables declaration//GEN-END:variables
}
