/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rent;
import java.sql.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.event.KeyEvent;

import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author User
 */
public class ReturnCarN extends javax.swing.JFrame {

    /**
     * Creates new form ReturnCarN
     */
    public ReturnCarN() {
        initComponents();
        table_update();
    }
        Connection conn;
        ResultSet rs;
        PreparedStatement pst;
        PreparedStatement pst1;
        PreparedStatement pst2;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtcarid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtcustid1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtelap = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtfine = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        button2 = new java.awt.Button();
        button1 = new java.awt.Button();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtcarid.setBackground(new java.awt.Color(248, 246, 246));
        txtcarid.setBorder(null);
        txtcarid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcaridActionPerformed(evt);
            }
        });
        txtcarid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcaridKeyPressed(evt);
            }
        });
        getContentPane().add(txtcarid, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 180, 30));

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(248, 246, 246));
        jLabel2.setText("Car Id");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 50, 30));

        txtcustid1.setBackground(new java.awt.Color(231, 232, 234));
        txtcustid1.setBorder(null);
        txtcustid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcustid1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtcustid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 190, 30));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(248, 246, 246));
        jLabel3.setText("Passenger ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 79, -1, 30));

        txtdate.setBackground(new java.awt.Color(231, 232, 234));
        txtdate.setBorder(null);
        getContentPane().add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 190, 30));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(248, 246, 246));
        jLabel4.setText("Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 40, 20));

        txtelap.setBackground(new java.awt.Color(231, 232, 234));
        txtelap.setBorder(null);
        getContentPane().add(txtelap, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 190, 30));

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(248, 246, 246));
        jLabel5.setText("Date Elapsed");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, 30));

        txtfine.setBackground(new java.awt.Color(231, 232, 234));
        txtfine.setBorder(null);
        txtfine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfineActionPerformed(evt);
            }
        });
        getContentPane().add(txtfine, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 190, 30));

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(248, 246, 246));
        jLabel6.setText("Fine");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 50, -1));

        button2.setBackground(new java.awt.Color(196, 167, 196));
        button2.setForeground(new java.awt.Color(255, 255, 255));
        button2.setLabel("Ok");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        getContentPane().add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 70, 30));

        button1.setBackground(new java.awt.Color(196, 167, 196));
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setLabel("Cancel");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 70, 30));

        jButton1.setBackground(new java.awt.Color(169, 195, 195));
        jButton1.setText("View Data");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 110, 30));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -540, 560, -1));

        jLabel8.setBackground(new java.awt.Color(231, 232, 234));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newcar/4593345dc4d90f9df9cf115938c64ae2.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void table_update()
{
    int c;
    try{
         Class.forName("com.mysql.jdbc.Driver");
         com.mysql.jdbc.Connection conn = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/carrental", "root", "");
         PreparedStatement pst = (PreparedStatement) conn.prepareStatement("select*from returncar");
         ResultSet rs = pst.executeQuery();
         ResultSetMetaData rd = rs.getMetaData();
         c= rd.getColumnCount();
         
          
           
       
    }catch(ClassNotFoundException | SQLException ex){
            Logger.getLogger(carRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    private void txtcaridKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcaridKeyPressed
        // TODO add your handling code here:

        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {

            try {
                Class.forName("com.mysql.jdbc.Driver");
                com.mysql.jdbc.Connection conn = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/carrental", "root", "");
                PreparedStatement pst = (PreparedStatement) conn.prepareStatement("select  cust_id,due,DATEDIFF(NOW(),due) as elap from rental where car_id=?");

                String car_id = txtcarid.getText();
                pst.setString(1,car_id);
                ResultSet rs = pst.executeQuery();
                if(rs.next()== false)
                {
                    JOptionPane.showMessageDialog(this,"Car ID not availabe");

                }else{
                    String custid = rs.getString("cust_id");
                    txtcustid1.setText(custid.trim());
                    String date= rs.getString("due");
                    txtdate.setText(date.trim());

                    String elap = rs.getString("elap");
                    int elaped = Integer.parseInt(elap);
                    if(elaped>0)
                    {
                        txtelap.setText(elap);
                        int fine = elaped * 100;
                        txtfine.setText(String.valueOf(fine));
                    }
                    else{
                        txtelap.setText("0");
                        txtfine.setText("0");
                    }
                }

            }catch(ClassNotFoundException ex) {
                Logger.getLogger(rental.class.getName()).log(Level.SEVERE, null, ex);
            }catch (SQLException ex) {
                Logger.getLogger(carRegistration.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_txtcaridKeyPressed

    private void txtcustid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcustid1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtcustid1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        String car_id = txtcarid.getText();
        String Cust_id = txtcustid1.getText();
        String date = txtdate.getText();
        String elp = txtelap.getText();
        String fine = txtfine.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver");

            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/carrental", "root", "");
            PreparedStatement pst = (PreparedStatement) conn.prepareStatement("insert into returncar(carid,custid,return_date,elap,fine)values(?,?,?,?,?)");
            pst.setString(1, car_id);
            pst.setString(2, Cust_id);
            pst.setString(3, date);
            pst.setString(4, elp);
            pst.setString(5, fine);
            pst.executeUpdate();

            java.sql.PreparedStatement pst1 = conn.prepareStatement("update carregistration set available ='Yes' where car_no=?");
            pst1.setString(1, car_id);
            pst1.executeUpdate();

            java.sql.PreparedStatement pst2 = conn.prepareStatement("Delete from rental where car_id=?");
            pst2.setString(1,car_id);
            pst2.executeUpdate();

            JOptionPane.showMessageDialog(this,"Car updated");
        }catch (ClassNotFoundException ex) {
            Logger.getLogger(rental.class.getName()).log(Level.SEVERE, null, ex);
        }catch (SQLException ex) {
            Logger.getLogger(carRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
                new CarRental().setVisible(true);
                this.dispose();
    }//GEN-LAST:event_button1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ReturncarTableData frametext = new ReturncarTableData();
        frametext.setVisible(true);
        frametext.pack();
        frametext.setLocationRelativeTo(null);
        frametext.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtcaridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcaridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcaridActionPerformed

    private void txtfineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnCarN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnCarN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnCarN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnCarN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnCarN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtcarid;
    private javax.swing.JTextField txtcustid1;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtelap;
    private javax.swing.JTextField txtfine;
    // End of variables declaration//GEN-END:variables
}
